# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RasterMerge
                                 A QGIS plugin
 Merge overlapping orthophotos and elevation models
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-10-21
        copyright            : (C) 2024 by UAV4GEO
        email                : pt@uav4geo.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'UAV4GEO'
__date__ = '2024-10-21'
__copyright__ = '(C) 2024 by UAV4GEO'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RasterMerge class from file RasterMerge.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .raster_merge import RasterMergePlugin
    return RasterMergePlugin()
